services:
  back:
    build: 
      context: ./backend
      target: dev
    ports:
      - 3005:80
    volumes:
      - ./backend/app:/code/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=db_user
      - DB_PASSWORD=password
      - DB_NAME=testing_app_db
    depends_on:
      db:
        condition: service_healthy
  
  front:
    build:
      context: ./frontend
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src

  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testing_app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    volumes:
      - ./mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 1m

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
